import { useInfiniteQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import staticWords from "@/data/words";
import type { CalvernProfile } from "@/services/calvernService";

export type FeedSort = "recent" | "popular" | "alpha";
export type FeedFilter = "all" | "prefix" | "suffix";

export interface FeedMorpheme {
  kind: string;
  form: string;
}

export interface FeedWord {
  id: string;
  word: string;
  definition: string;
  origin: string;
  morphemes: FeedMorpheme[];
  imageUrl: string | null;
}

const PAGE_SIZE = 24;

// Photos that shipped with the original built-in words, kept as a fallback image source.
const staticImages = new Map(staticWords.map((w) => [w.word.toLowerCase(), w.images?.[0]?.url ?? null]));

interface Row {
  id: string;
  word: string;
  profile: CalvernProfile | null;
  definitions: { primary?: string } | null;
  etymology: { language_of_origin?: string } | null;
  morpheme_breakdown: Record<string, { text?: string } | undefined> | null;
  image_url: string | null;
}

// Legacy rows (not yet regenerated by Calvern) still show their old prefix/root/suffix.
function legacyMorphemes(mb: Row["morpheme_breakdown"]): FeedMorpheme[] {
  if (!mb) return [];
  return (["prefix", "root", "suffix"] as const)
    .filter((k) => mb[k]?.text)
    .map((k) => ({ kind: k, form: mb[k]!.text! }));
}

function toFeedWord(r: Row): FeedWord {
  const word = r.word.toLowerCase();
  return {
    id: r.id,
    word,
    definition: r.profile?.definitions.primary ?? r.definitions?.primary ?? "",
    origin: r.profile?.etymology.language_of_origin ?? r.etymology?.language_of_origin ?? "",
    morphemes: r.profile?.morphemes.map((m) => ({ kind: m.kind, form: m.form })) ?? legacyMorphemes(r.morpheme_breakdown),
    imageUrl: r.image_url ?? staticImages.get(word) ?? null,
  };
}

// Paged feed of word profiles straight from the database (the single source of truth).
export function useWordFeed(sort: FeedSort, filter: FeedFilter) {
  return useInfiniteQuery({
    queryKey: ["word-feed", sort, filter],
    initialPageParam: 0,
    queryFn: async ({ pageParam }) => {
      let q = supabase
        .from("word_profiles")
        .select("id, word, profile, definitions, etymology, morpheme_breakdown, image_url", { count: "exact" })
        .eq("status", "active");
      if (filter !== "all") q = q.contains("profile", { morphemes: [{ kind: filter }] });
      q =
        sort === "popular"
          ? q.order("lookup_count", { ascending: false }).order("word")
          : sort === "alpha"
            ? q.order("word")
            : q.order("created_at", { ascending: false });
      const { data, error, count } = await q.range(pageParam, pageParam + PAGE_SIZE - 1);
      if (error) throw error;
      return { words: (data as Row[]).map(toFeedWord), count: count ?? 0, next: pageParam + PAGE_SIZE };
    },
    getNextPageParam: (last) => (last.next < last.count ? last.next : undefined),
  });
}
