
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pivvbookarqnqynfmaxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpdnZib29rYXJxbnF5bmZtYXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjMxMDQsImV4cCI6MjA1NzQzOTEwNH0.wm9dimQTjCGUG1vPuO2K0XPkbfP-iK5QLOWxQc-GmQM";

// Create a generic Supabase client to handle any database schema
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
