// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sehrwrwkrwyibxlicpsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlaHJ3cndrcnd5aWJ4bGljcHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTIzODMsImV4cCI6MjA2NTEyODM4M30.vk3R01pB0CcUR8jXHvTJHHrjhW8eyCMWc9BVvWuoPdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);